version: '3.8'

services:
  node:
    container_name: node
    image: home-library-service:node
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.node
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/app/src
    networks:
      - node-postgres-bridge
  postgres:
    container_name: postgres
    image: home-library-service:postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
        - db:/var/lib/postgresql/data
        - db-logs:/var/logs/postgresql
    networks:
      - node-postgres-bridge

volumes:
  db:
  db-logs:

networks:
  node-postgres-bridge:
    driver: bridge